version: '2'

services:

  db:
    build: postgres
    ports:
      - "6432:5432"
    volumes_from:
      - data

  redis:
    image: redis

  esclient:
    build: ./elasticsearch/
    # image: eeacms/elastic:bise
    command: # Single node
          - elasticsearch
          - -Des.node.data=true
          - -Des.http.enabled=true
          - -Des.node.master=true
          - -Des.node.river=_none_
          - -Des.transport.tcp.compress=true
          - -Des.http.max_content_length=100mb
    ports:
      - "9200:9200"
    volumes_from:
      - data

  web:
    image: eeacms/bise.catalogue:latest
    # build: ./src/bise.catalogue
    environment:
      - RAILS_ENV=development
    command: sh -c "rm /app/tmp/pids/server.pid && rails server"
    volumes:
      - ./src/bise.catalogue:/app
      - ./config/overrides/ldap.yml:/app/config/ldap.yml
      - ./config/overrides/database.yml:/app/config/database.yml
      - ./config/overrides/elasticsearch.yml:/app/config/elasticsearch.yml
      - ./config/overrides/redis.yml:/app/config/redis.yml
      - ./config/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./var/tmp:/app/tmp
      - ./var/log-web:/app/log
    volumes_from:
      - data
    ports:
      - "4000:3000"

  webprod:
    image: eeacms/bise.catalogue:latest
    environment:
      - RAILS_ENV=production
      - BISE_DEVEL=on
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./var/tmp-prod:/app/tmp:rw
      - ./var/log-webprod:/app/log:rw
    volumes_from:
      - web
    ports:
      - "5000:3000"

  worker:
    image: eeacms/bise.catalogue:latest
    environment:
      - RAILS_ENV=production
    command: bundle exec sidekiq -L /app/log/sidekiq.log -q default -e development
    volumes:
      - ./var/log-worker:/app/log
    volumes_from:
      - web

  data:
    build: ./data
    volumes:
      - ./snapshots:/snapshots:z
      - ./var/tmp:/tmp

# - ./src/devproduction.rb:/app/config/environments/production.rb:rw
