db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
elasticsearch:
  build: elasticsearch
  command: 
    - elasticsearch
    - Des.cluster.name="Catalogue Cluster"
    - Des.node.name="Catalogue Master Node"
    - Des.node.master=true
    - Des.index.number_of_shards=5
    - Des.index.number_of_replicas=1
    - Des.transport.tcp.compress=true
    - Des.http.max_content_length=100mb
  ports:
    - "9200:9200"
web:
  build: bise-catalogue
  environment:
    - RAILS_ENV=production
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
    - elasticsearch
    - redis
worker:
  build: bise-catalogue
  environment:
    - RAILS_ENV=production
  command: bundle exec sidekiq -d -L log/sidekiq.log -q default -e production
  links:
    - db
    - redis
