version: "2"

services:

  # NGINX frontend
  frontend:
    image: eeacms/bise.catalogue:frontend-
    links:
      - web
    volumes:
      uploads-data:/app/public

  esclient:
    image: eeacms/bise.catalogue:elasticsearch-
    restart: always
    command: # Single node
        - elasticsearch
        - -Des.node.data=true
        - -Des.http.enabled=true
        - -Des.node.master=true
        - -Des.node.river=_none_
        - -Des.transport.tcp.compress=true
        - -Des.http.max_content_length=100mb
    volumes:
      - elasticsearch-snapshots:/snapshots:z
    ports:
      - 19200:9200

  db:
    image: postgres:8.4
    restart: always
    ports:
      - 15432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  postfix:
    image: eeacms/postfix:eionet
    restart: always

  # The main RubyOnRails based CMS
  web:
    image: eeacms/bise.catalogue:latest
    restart: always
    environment:
      - RAILS_ENV=production
    ports:
      - 50000:3000
    volumes:
      - ./config/production/config/ldap.yml:/app/config/ldap.yml
      - ./config/overrides/database.yml:/app/config/database.yml
      - ./config/overrides/elasticsearch.yml:/app/config/elasticsearch.yml
      - ./config/overrides/redis.yml:/app/config/redis.yml
      - ./config/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./var/web:/app/tmp/
      #- ./production.rb:/app/config/environments/production.rb
    volumes_from:
      - data
    links:
      - db
      - esclient
      - redis
      - postfix

  # sidekiq based worker "instance"
  worker:
    image: eeacms/bise.catalogue:latest
    restart: always
    environment:
      - RAILS_ENV=production
    command: bundle exec sidekiq -L log/sidekiq.log -q default -e production
    volumes:
      - ./config/production/config/ldap.yml:/app/config/ldap.yml
      - ./config/overrides/database.yml:/app/config/database.yml
      - ./config/overrides/elasticsearch.yml:/app/config/elasticsearch.yml
      - ./config/overrides/redis.yml:/app/config/redis.yml
      - ./config/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    volumes_from:
      - data
    links:
      - db
      - esclient
      - redis

  # Data volume container
  data:
    build: data

  # dataes:
  #   image: busybox
  #   volumes:
  #     - /usr/share/elasticsearch/data

 volumes:
   elasticsearch-data:
   elasticsearch-snapshots:
   postgresql-data:
   uploads-data:
