db:
  image: postgres:8.4
  ports:
    - "5432"
  volumes_from:
    - data
redis:
  image: redis
esclient:
    image: eeacms/elastic:bise
    restart: always
    command: # Single node
      - elasticsearch
      - -Des.node.data=true
      - -Des.http.enabled=true
      - -Des.node.master=true
      - -Des.node.river=_none_
      - -Des.transport.tcp.compress=true
      - -Des.http.max_content_length=100mb
    volumes_from:
      - data
    ports:
      - 9200:9200
# Ruby on Rails config
web:
  image: eeacms/bise.catalogue:lastest
  restart: always
  environment:
    - RAILS_ENV=development
  volumes:
    - ./src/bise.catalogue:/app
  volumes_from:
    - data
  ports:
    - "3000:3000"
  links:
    - db
    - esclient
    - redis
worker:
  image: eeacms/bise.catalogue:lastest
  restart: always
  environment:
    - RAILS_ENV=development
  command: bundle exec sidekiq -L log/sidekiq.log -q default -e development
  volumes:
    - ./src/bise.catalogue:/app
  volumes_from:
    - data
  links:
    - db
    - esclient
    - redis
# Data volume container
data:
  build: data
