db:
  image: postgres:8.4
  restart: always
  ports:
    - "5432"
  volumes_from:
    - data
redis:
  image: redis
  restart: always
postfix:
  image: eeacms/postfix:eionet
  restart: always
  env_file: .secret
# ElasticSearch config
esmaster:
    image: eeacms/elastic:bise
    restart: always
    command: # No data, no http, no river, can be master
      - elasticsearch
      - Des.node.data=false
      - Des.http.enabled=false
      - Des.node.master=true
      - Des.node.river=_none_
esclient:
    image: eeacms/elastic:bise
    restart: always
    command: # No data, http, no river, can't be master
      - elasticsearch
      - -Des.node.data=false
      - -Des.http.enabled=true
      - -Des.node.master=false
      - -Des.node.river=_none_
      - -Des.transport.tcp.compress=true
      - -Des.http.max_content_length=100mb
    ports:
      - 9200:9200
esworker1:
    image: eeacms/elastic:bise
    restart: always
    command: # Data, no http, river, can't be master
        - elasticsearch
        - Des.node.data=true
        - Des.http.enabled=false
        - Des.node.master=false
    volumes_from:
        - dataw1
    environment:
        - ES_HEAP_SIZE=2g
dataw1:
    image: busybox
    volumes:
        - /usr/share/elasticsearch/data
esworker2:
    image: eeacms/elastic:bise
    restart: always
    command: # Data, no http, river, can't be master
        - elasticsearch
        - -Des.node.data=true
        - -Des.http.enabled=false
        - -Des.node.master=false
    volumes_from:
        - dataw2
    environment:
        - ES_HEAP_SIZE=2g
dataw2:
    image: busybox
    volumes:
        - /usr/share/elasticsearch/data
# Alternative single container setup:
#esclient:
#    image: eeacms/elastic:bise
#    restart: always
#    command: # Single node
#      - elasticsearch
#      - -Des.node.data=true
#      - -Des.http.enabled=true
#      - -Des.node.master=true
#      - -Des.node.river=_none_
#      - -Des.transport.tcp.compress=true
#      - -Des.http.max_content_length=100mb
#    volumes_from:
#      - data
#    ports:
#      - 9200:9200
# Ruby on Rails config
web:
  image: eeacms/bise.catalogue:latest
  restart: always
  environment:
    - RAILS_ENV=production
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - ./bise-catalogue/config/ldap.yml:/app/config/ldap.yml
    - ./bise-catalogue/config/database.yml:/app/config/database.yml
    - ./bise-catalogue/config/elasticsearch.yml:/app/config/elasticsearch.yml
    - ./bise-catalogue/config/redis.yml:/app/config/redis.yml
    - ./bise-catalogue/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    #- ./production.rb:/app/config/environments/production.rb
  volumes_from:
    - data
  links:
    - db
    - esclient
    - redis
    - postfix
worker:
  image: eeacms/bise.catalogue:latest
  restart: always
  environment:
    - RAILS_ENV=production
  command: bundle exec sidekiq -L log/sidekiq.log -q default -e production
  volumes:
    - ./bise-catalogue/config/ldap.yml:/app/config/ldap.yml
    - ./bise-catalogue/config/database.yml:/app/config/database.yml
    - ./bise-catalogue/config/elasticsearch.yml:/app/config/elasticsearch.yml
    - ./bise-catalogue/config/redis.yml:/app/config/redis.yml
  volumes_from:
    - data
  links:
    - db
    - esclient
    - redis
# NGINX frontend
frontend:
    build: frontend
    restart: always
    links:
        - web
    volumes_from:
        - web
        - data
    ports:
        - 80:80
# Data volume container
data:
  build: data
