db:
  image: postgres:8.4
  ports:
    - "5432"
  volumes_from:
    - data
redis:
  image: redis
# ElasticSearch config
esmaster:
    image: eeacms/elastic:bise
    restart: always
    command: # No data, no http, no river, can be master
      - elasticsearch
      - Des.node.data=false
      - Des.http.enabled=false
      - Des.node.master=true
      - Des.node.river=_none_
esclient:
    image: eeacms/elastic:bise
    restart: always
    command: # No data, http, no river, can't be master
      - elasticsearch
      - -Des.node.data=false
      - -Des.http.enabled=true
      - -Des.node.master=false
      - -Des.node.river=_none_
      - -Des.transport.tcp.compress=true
      - -Des.http.max_content_length=100mb
    ports:
      - 9200:9200
esworker1:
    image: eeacms/elastic:bise
    restart: always
    command: # Data, no http, river, can't be master
        - elasticsearch
        - Des.node.data=true
        - Des.http.enabled=false
        - Des.node.master=false
    volumes_from:
        - data
    environment:
        - ES_HEAP_SIZE=2g
# Ruby on Rails config
web:
  image: eeacms/bise.catalogue:assets
  environment:
    - RAILS_ENV=production
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - ./bise-catalogue/config/ldap.yml:/app/config/ldap.yml
    - ./bise-catalogue/config/database.yml:/app/config/database.yml
    - ./bise-catalogue/config/elasticsearch.yml:/app/config/elasticsearch.yml
    - ./bise-catalogue/config/redis.yml:/app/config/redis.yml
    - ./production.rb:/app/config/environments/production.rb
  volumes_from:
    - data
  ports:
    - "3000:3000"
  links:
    - db
    - esclient
    - redis
worker:
  image: eeacms/bise.catalogue:latest
  environment:
    - RAILS_ENV=production
  command: bundle exec sidekiq -d -L log/sidekiq.log -q default -e production
  volumes:
    - ./bise-catalogue/config/ldap.yml:/app/config/ldap.yml
    - ./bise-catalogue/config/database.yml:/app/config/database.yml
    - ./bise-catalogue/config/elasticsearch.yml:/app/config/elasticsearch.yml
    - ./bise-catalogue/config/redis.yml:/app/config/redis.yml
  volumes_from:
    - data
  links:
    - db
    - esclient
    - redis
# Data volume container
data:
  build: data