production: &default
  adapter: postgresql
  encoding: unicode
  database: catalogue_production
  pool: 5
  host: db
  username: postgres
  password:

development: &default
  adapter: postgresql
  database: catalogue_development
  host: db
  username: postgres
  password:
