authorizations: &AUTHORIZATIONS
  # group_base: ou=groups,dc=test,dc=com
  group_base: ou=Roles,o=EIONET,l=Europe
  required_groups:
    - cn=extranet-bise-cat-read,cn=extranet-bise-cat,cn=extranet-bise,cn=extranet,ou=Roles,o=EIONET,l=Europe
  require_attribute:
    objectClass: top
    authorizationRole: uniqueMember

production:
  host: ldap4.eionet.europa.eu
  port: 389
  attribute: uid
  base: ou=Users,o=EIONET,l=Europe
  admin_user: uid=catalogue_app,ou=Users,o=EIONET,l=Europe
  admin_password: <%= ENV["LDAP_PRODUCTION_PASSWORD"] %>
  ssl: false
  <<: *AUTHORIZATIONS

development:
  host: ldap4.eionet.europa.eu
  port: 389
  attribute: uid
  base: ou=Users,o=EIONET,l=Europe
  admin_user: uid=catalogue_app,ou=Users,o=EIONET,l=Europe
  admin_password: <%= ENV["LDAP_PRODUCTION_PASSWORD"] %>
  ssl: false
  <<: *AUTHORIZATIONS
